CREATE DATABASE korona

CREATE TABLE USERS(
     ID INT PRIMARY KEY AUTO_INCREMENT,
    `NAME` VARCHAR(256),
     EMAIL VARCHAR(256) ,
     AGE INT,
    `ADDRESS`  VARCHAR(256),
    `PASSWORD`  VARCHAR(256),
    USER_TYPE_ID INT,FOREIGN KEY(USER_TYPE_ID) REFERENCES USER_TYPE(ID)
);

CREATE TABLE HOSPITAL(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    HOSPITAL_NAME VARCHAR(256) UNIQUE,
   `ADDRESS` VARCHAR(256)
);

CREATE TABLE VACCINATION(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VACCINE VARCHAR(256) UNIQUE,
    `STATUS` BIT DEFAULT 1
);

CREATE TABLE USER_TYPE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    `TYPE` VARCHAR(256) 
);


CREATE TABLE APPOINTMENT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT ,FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    HOSPITAL_ID INT ,FOREIGN KEY(HOSPITAL_ID) REFERENCES HOSPITAL(ID),
    VACCINE_ID INT ,FOREIGN KEY(VACCINE_ID) REFERENCES VACCINATION(ID),
    ANY_DISEASE VARCHAR(256),
    GENDER BIT,
    `STATUS` BIT
    -- 1 = BOY    0 = GIRL 
);

CREATE TABLE approved_appointment(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(256) ,
    HOSPITAL_NAME VARCHAR(256) ,
    VACCINE VARCHAR(256) ,
    ANY_DISEASE VARCHAR(256),
    GENDER BIT
    -- 1 = BOY    0 = GIRL 
);

CREATE TABLE CONTACT (
ID INT AUTO_INCREMENT PRIMARY KEY,
`NAME` VARCHAR(256),
EMAIL VARCHAR(256),
`SUBJECT` VARCHAR(256),
PHONE VARCHAR(256),
HOSPITAL VARCHAR(256),
`MESSAGE` VARCHAR(256) NOT NULL
)